### ISSUE TITLE
using large file unity very slow

### ISSUE THREAD

**Issue by fingerx** [unity3d-jp/StreamingImageSequence#1]
file type:png
size :6208X2304
unity version:2018.3.x
pc:win10,ssd hard,p3200,i7-8750,16g ram

![image](https://user-images.githubusercontent.com/5524551/54115189-fcaaaa80-4426-11e9-96a1-41d73f3d68fb.png)

**Comment by sindharta** [comment]
Can you please elaborate ? 
How slow is this ? Perhaps you can also share your project?

**Comment by sindharta** [comment]
I am closing this issue due to non-activity.
Please let us know if you still have the same issue using the latest version.
