### ISSUE TITLE
using new version cant load huge imageSequence

### ISSUE THREAD

**Issue by fingerx** [unity3d-jp/StreamingImageSequence#46]
I remember in the previous version that sequence frames could not be imported into the AssetStreaming folder, but this is now necessary. This design is really too bad for huge data. I have 64GB of sequential frame data and the new version cannot be imported.

**Comment by sindharta** [comment]
> I remember in the previous version that sequence frames could not be imported into the AssetStreaming folder, but this is now necessary.

No, copying to StreamingAssets folder is not always necessary.
Please take a look at our [importing images](https://github.com/unity3d-jp/StreamingImageSequence/blob/dev/Documentation~/en/ImportingImages.md#setting-the-folder-via-inspector) page.

**Comment by fingerx** [comment]
ok,thanks
